import "./globals.css";
import Topbar from "./components/Topbar";
import { Footer } from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Topbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
