// Bilingual copy for the booking page.

export const BOOK_COPY = {
  en: {
    eyebrow: "Book the Private Space",
    title: "Reserve your time.",
    subtitle: "Pick a date, choose how long, tell us a little about your work. We reply within 24 hours.",
    sections: {
      date: "1 · Pick your date",
      bookingType: "2 · How long?",
      time: "3 · Time of day",
      details: "4 · About your booking",
      contact: "5 · Your details",
      promo: "Have a promo code?",
      summary: "Summary",
    },
    bookingTypes: {
      hourly: { label: "By the hour", hint: "2-hour minimum, 4+ hours discounted" },
      half_day: { label: "Half-day · 4 hrs", hint: "Morning, afternoon, or evening block" },
      full_day: { label: "Full day · 8+ hrs", hint: "The room is yours from morning to night" },
      recurring_weekly: { label: "Weekly slot", hint: "Hold the same hours every week, billed monthly" },
    },
    fields: {
      startTime: "Start time",
      durationHours: "Duration (hours)",
      hoursPerWeek: "Hours per week",
      weekday: "Day of the week",
      practiceType: "What's the room for?",
      practiceDescription: "Tell us a little more (optional)",
      groupSize: "Group size",
      name: "Your name",
      email: "Email",
      phone: "Phone",
      promoCode: "Promo code",
      submit: "Send booking request",
      submitting: "Sending…",
    },
    weekdays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    practiceOptions: [
      { value: "therapy", label: "Therapy / counseling" },
      { value: "coaching", label: "Coaching / consulting" },
      { value: "bodywork", label: "Massage / bodywork" },
      { value: "energy", label: "Energy work / healing" },
      { value: "circle", label: "Small circle / ceremony" },
      { value: "lesson", label: "Private lesson" },
      { value: "shoot", label: "Photoshoot / podcast" },
      { value: "other", label: "Other" },
    ],
    legal: "By submitting, you agree to our cancellation policy: full refund 7+ days out, 50% within 48 hours, none under 48 hours.",
    summary: {
      subtotal: "Subtotal",
      discount: "Discount",
      total: "Total",
      monthly: "/ month",
      pendingNote: "We'll review your request within 24 hours and email a payment link.",
    },
    success: {
      title: "Request received.",
      body: "We'll review and get back to you within 24 hours. Check your inbox — a confirmation is on its way.",
      backHome: "Back to The Private Space",
    },
    errors: {
      pickDate: "Please pick a date.",
      pickTime: "Please pick a start time.",
      pickDuration: "Please choose a duration.",
      missingContact: "Name and email are required.",
      submitFailed: "Something went wrong — please try again or call 616 7722.",
    },
  },
  is: {
    eyebrow: "Bóka Einkarýmið",
    title: "Frátaktu þinn tíma.",
    subtitle: "Veldu dagsetningu, lengd, og segðu okkur aðeins frá vinnunni þinni. Við svörum innan 24 klst.",
    sections: {
      date: "1 · Veldu dagsetningu",
      bookingType: "2 · Hve lengi?",
      time: "3 · Tími dagsins",
      details: "4 · Um bókunina",
      contact: "5 · Upplýsingar þínar",
      promo: "Ertu með afsláttarkóða?",
      summary: "Yfirlit",
    },
    bookingTypes: {
      hourly: { label: "Tímabreytt", hint: "Lágmark 2 klst, afsláttur frá 4+ klst" },
      half_day: { label: "Hálfur dagur · 4 klst", hint: "Morgun, síðdegi eða kvöld" },
      full_day: { label: "Heill dagur · 8+ klst", hint: "Rýmið er þitt allan daginn" },
      recurring_weekly: { label: "Vikulegur tími", hint: "Sömu klukkustundir hverja viku, mánaðarleg rukkun" },
    },
    fields: {
      startTime: "Upphafstími",
      durationHours: "Lengd (klst)",
      hoursPerWeek: "Klst á viku",
      weekday: "Dagur vikunnar",
      practiceType: "Til hvers er rýmið?",
      practiceDescription: "Segðu okkur aðeins meira (valfrjálst)",
      groupSize: "Hópastærð",
      name: "Nafn þitt",
      email: "Netfang",
      phone: "Sími",
      promoCode: "Afsláttarkóði",
      submit: "Senda bókunarbeiðni",
      submitting: "Sendi…",
    },
    weekdays: ["Mánudagur", "Þriðjudagur", "Miðvikudagur", "Fimmtudagur", "Föstudagur", "Laugardagur", "Sunnudagur"],
    practiceOptions: [
      { value: "therapy", label: "Meðferð / ráðgjöf" },
      { value: "coaching", label: "Þjálfun / ráðgjöf" },
      { value: "bodywork", label: "Nudd / líkamsvinna" },
      { value: "energy", label: "Orkuvinna / heilun" },
      { value: "circle", label: "Lítill hringur / athöfn" },
      { value: "lesson", label: "Einkatími" },
      { value: "shoot", label: "Myndataka / hlaðvarp" },
      { value: "other", label: "Annað" },
    ],
    legal: "Með því að senda samþykkir þú afbókunarstefnu: full endurgreiðsla 7+ daga fyrir, 50% innan 48 klst, engin undir 48 klst.",
    summary: {
      subtotal: "Undirhlutfall",
      discount: "Afsláttur",
      total: "Samtals",
      monthly: "/ mánuði",
      pendingNote: "Við yfirförum beiðni þína innan 24 klst og sendum greiðslulink.",
    },
    success: {
      title: "Beiðni móttekin.",
      body: "Við yfirförum og svörum innan 24 klst. Athugaðu pósthólfið — staðfesting er á leiðinni.",
      backHome: "Til baka á Einkarýmið",
    },
    errors: {
      pickDate: "Veldu dagsetningu.",
      pickTime: "Veldu upphafstíma.",
      pickDuration: "Veldu lengd.",
      missingContact: "Nafn og netfang eru nauðsynleg.",
      submitFailed: "Eitthvað fór úrskeiðis — reyndu aftur eða hringdu í 616 7722.",
    },
  },
};
