"use client";

import { motion } from "framer-motion";
import { format } from "date-fns";

// ─────────────────────────────────────────────────────────────
// TribeCardVisual — "Cream & botanical" (Sept 2026)
// ─────────────────────────────────────────────────────────────
// The same card in every place it appears:
//   • Apple / Google Wallet  (src/lib/applePass.js, googleWallet.js)
//   • /tribe-card/[token] and /profile/my-tribe-card   (this component)
//   • the card email                                    (TribeCardWelcome.jsx)
//
// Anatomy, mirroring the Wallet pass so people recognise it instantly:
//   header  — the hand-written "Mama" script + "Tribe"
//   band    — cream strip with the full wreath at the right; the discount
//             sits on the left of the band
//   fields  — Member · Valid until
// Images come from /public/wallet-pass (generated by
// scripts/generate-wallet-pass-images.py from the master logo).
// ─────────────────────────────────────────────────────────────

const SCRIPT_SRC = "/wallet-pass/logo@3x.png";
const STRIP_SRC = "/wallet-pass/strip@3x.png";

function statusLabel(card) {
  if (card.status === "revoked") return "Revoked";
  if (card.status === "expired") return "Expired";
  if (card.expires_at && new Date(card.expires_at) < new Date()) return "Expired";
  return "Active";
}

export default function TribeCardVisual({ card }) {
  if (!card) return null;

  const { holder_name, discount_percent, expires_at, source } = card;
  const status = statusLabel(card);
  const isActive = status === "Active";
  const isPaid = source === "paid-tribe";

  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
      className="relative w-full max-w-[375px] rounded-[22px] overflow-hidden"
      style={{
        background: "#f9f4ec",
        boxShadow:
          "0 24px 48px -18px rgba(44,24,16,0.45), 0 2px 8px rgba(44,24,16,0.08)",
        filter: isActive ? "none" : "saturate(0.35)",
        opacity: isActive ? 1 : 0.9,
      }}
    >
      {/* Header — script wordmark + Tribe */}
      <div className="flex items-center justify-between px-5 pt-[18px] pb-3">
        <img
          src={SCRIPT_SRC}
          alt="Mama"
          style={{ height: 34, width: "auto", display: "block" }}
        />
        <span className="text-[15px] text-[#2c1810]">Tribe</span>
      </div>

      {/* Band — the wreath strip with the discount on it */}
      <div
        className="relative"
        style={{
          aspectRatio: "375 / 123",
          backgroundImage: `url(${STRIP_SRC})`,
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      >
        <div className="absolute left-5 bottom-3.5">
          <p className="text-[11px] tracking-[0.08em] uppercase text-[#1f5c4b] font-semibold">
            {isActive ? "Member discount" : status}
          </p>
          <p
            className="leading-none text-[#2c1810] font-light"
            style={{ fontSize: 54, letterSpacing: "-0.02em" }}
          >
            {isActive ? `${discount_percent}%` : "—"}
          </p>
        </div>
      </div>

      {/* Fields */}
      <div className="flex gap-7 px-5 pt-[18px]">
        <div>
          <p className="text-[11px] tracking-[0.06em] uppercase text-[#1f5c4b] font-semibold">
            Member
          </p>
          <p className="text-[15px] text-[#2c1810] mt-[3px]">{holder_name}</p>
        </div>
        <div>
          <p className="text-[11px] tracking-[0.06em] uppercase text-[#1f5c4b] font-semibold">
            Valid until
          </p>
          <p className="text-[15px] text-[#2c1810] mt-[3px]">
            {expires_at ? format(new Date(expires_at), "d MMMM yyyy") : "Always"}
          </p>
        </div>
      </div>

      <p className="px-5 pt-[22px] text-[12px] text-[#7a6a5a]">
        Show at the counter before paying · food &amp; drinks
      </p>
      <p
        className="px-5 pt-5 pb-[18px] italic text-[15px] text-[#9a8e82]"
        style={{ fontFamily: "Cormorant Garamond, Georgia, serif" }}
      >
        {isPaid ? "Renews with your membership · " : ""}Plant-based · Reykjavík · Made with love
      </p>
    </motion.div>
  );
}
